### ISSUE TITLE
What causes green LED to blink?

### ISSUE THREAD

**Issue by a2life** [cubieplayer/Cubian#204]
For the last 30 days or so, I saw two occasions of green LED blinking when I wake up in the morning.  In both cases Cubie is working just fine as mail/web server.   In both cases I see LED trigger is set to [timer].  (in /sys/class/leds/ folder) So I can turn off the LED by setting "trigger" to [none].  I would like to know the cause of this.  So this is more of a question.  What causes Cubian to set green LED to blink?

**Comment by cubieplayer** [comment]
https://github.com/cubieplayer/Cubian/wiki/Get-started-with-Cubian
- The green LED indicate system status. If this LED blinking every 1 second, it means the system is starting up or shutting down normally, after the system has started this LED turns to indicates the SD-card r/w status.

**Comment by a2life** [comment]
Then here is a strange part. the system is running for many days, the all service seems to be normally run, but green LED blinking every 1 seconds. I noticed this morning and maybe 20 days ago.  as I indicated above, when I look into /sys/class/leds/green:ph20:led1, trigger is set to [timer] and  brightness is set to 1.  Its not in the process of either starting up or shutting down. SD card is not present in my configuration. /boot is in nand and rootfs is in sda1.

**Comment by rewindustry** [comment]
happens here also, running from SDcard.  goes away after a reboot.

**Comment by rewindustry** [comment]
apparently controlled by service cubian-bootled - you can turn it off by running:

sudo service cubian-bootled start

the problem is that the script turns the flash back on whenever called to do anything other than "start", including "status" - this is probably what keeps turning it back on, apparently at "random".

i have removed "status" as an option from the case switch in /etc/init.d/cubian-bootled on my system, and will report back if this does not solve the problem.
