### ISSUE TITLE
cubian-update bug

### ISSUE THREAD

**Issue by s-kostyuk** [cubieplayer/Cubian#233]
I have reinstalled latest Cubian from SD-card on Cubieboard 1 NAND about a month ago. No with cubian-update I get this error:
`error: can't update, failed to detect system type`
How to diagnose and fix this problem?

**Comment by cubieplayer** [comment]
cubian-update will be abandoned, the update will be managed totally by apt

**Comment by s-kostyuk** [comment]
So, we need just wait for realization of new update mechanism? OK :)

**Comment by s-kostyuk** [comment]
Fix for users (example for nand):
Change in /etc/fstab one line from
`UUID="d4c8f681-2193-44ab-9f6b-77f2c62f156b"    /      ext4     defaults    0    1`
to
`/dev/nanda    /      ext4     defaults    0    1`

This must help

OR

Edit /usr/sbin/cubian-update (dirty hack):
1.Open file in any editor from root (nano for example):

```
sudo nano /usr/sbin/cubian-update
```

2.Set this valuable manually (line 85):

```
SYS_INSTALL_TYPE="nand"
```

3.Comment this lines (from 746 to 750):

```
#determineSysInstallType
#if [[ -z $SYS_INSTALL_TYPE ]];then
#       echoRed "error: can't update, failed to detect system type"
#       exit
#fi
```

4.Now you can start cubian-update

**Comment by s-kostyuk** [comment]
Sorry. /dev/nandb, not /dev/nanda in fstab must be.

**Comment by Daniel-Brosnan** [comment]
My Cubieboard has the rootfs in a USB and I thought it was necessary to modify the /etc/fstab file to indicate the / partition is /dev/sda1 (The USB device) but it's not. So following your suggestions, and thinking that I had already checked this I left the original content of the /etc/fstab file with the line:
 /dev/mmcblk0p1          /               ext4    defaults        0       1
and cubian-update works. So a general solution could be not modify the /etc/fstab.

**Comment by s-kostyuk** [comment]
Now cubian-update, I think, doesn't support rootfs on USB or SATA drive and looks only for two options in fstab: /dev/nanda or /dev/mmcblk0p1. So if no one of this strings will be found then cubian-update returns "error: can't update, failed to detect system type".

**Comment by rewindustry** [comment]
in around line 740 of cubian-update script - the $BRANCH variable must be wrapped in doublequotes, or the -z test will always return false.  quite a number of such tests are broken in this script, leading to the question:

HAS THIS SCRIPT EVER BEEN TESTED?

my patches to date should fix the above, and also should add recognition for usb and sata mounts, in that it will now check for /dev/sd.. mounts in fstab, as well as the usual suspects.

please note the result simply turns off the bootLoader update altogether, because at this point we have no idea if booted from nand or sd-card.

please _also_ note that uImage is now updated in /boot on your drive, but you are actually booting from the uImage in nand, or on your sd-card - again it cannot tell which is correct, so you will have to push this update manually also.

http://pastebin.com/hF0EYeEg

no guarantees - make a backup and/or recovery plan first.
