### ISSUE TITLE
Cubian Text Only Random Crash

### ISSUE THREAD

**Issue by hollstar** [cubieplayer/Cubian#266]
RE: Linux Cubian 3.4.75-sun7i #36 SMP PREEMPT Mon Feb 10 02:47:28 CST 2014 armv7l GNU/Linux

Hi everyone,
I have Cubian running off an SD card at present and have noticed is randomly crashes without any real warning. The system can be essentially idle whilst I monitor htop and it will simply freeze. I've already updated it to deal with the previously mentioned crash issue however this has not rectified the problem.

What information can I provide which would help developers get to the bottom of this?

**Comment by nightsuns** [comment]
me too.

while cpu 100% long for a while, i will could not ping cubieboard anymore.

**Comment by hollstar** [comment]
I'd be more than happy to work with those contributing on determining what the issue here is. The only thing I've been testing at this point is an rsync operation from a VPS. The time it takes for the system to freeze differs each time and simply isn't consistent. I've had the board powered by a USB hub which generates more power than is necessary and also directly off the USB port of another system. Neither seems to be more reliable than the other.

**Comment by nightsuns** [comment]
i just using a psp 2A power, so the power of cause is fine.

i used ubuntu at past, it works well. yesterday i changed to cubian.
i found if cpu is high(also tested in the old ubuntu), the bug is
more reappear, i am compiling a large software on board.just doing make for
a while.

the enveriment is:

cubian install on a 16G sd card.
and compiling software on a external sata disk(200G).

hope this information is usefull for you.

**Comment by michalliu** [comment]
1. http://cubian.org/2013/09/18/fix-random-crash/
2. http://cubian.org/2014/07/05/resolve-stability-issue-on-cb2
