### ISSUE TITLE
cubian-nandinstall is not working for Cubietruck

### ISSUE THREAD

**Issue by joetruck** [cubieplayer/Cubian#301]
Installing Cubian (Desktop) to nand, as descript in the tutorial, is not working. After running cubian-nandinstall on restart only the red power led is on, and the board is not booting. i have recovered the nand Storage with LUBUNTU  via PHOENIX-SUIT and tried to run cubian-nandinstall again, with the same result no boot from nand. I am using the cubietruck with 8 gb nand 2 gb ram+ bluetooth. 
i would like to transfer the system vom my ySD card to the nand storage. I am a Newby to Linux so please if someone could provide me a step by step description for a workaround.
Thanx
JOE

**Comment by joetruck** [comment]
Update:
I have managed now to transfer the image successfully to the nand storage.  I dont no exactly what was the cause because I tried out several times to transfer it. When it failed I flashed again Lubuntu with the Phoenix suit and tried again. 
I found in the German debianforum that there are troubles with other distro's too. http://debianforum.de/forum/viewtopic.php?f=1&t=148369 
In one of the cases it is needed to place this https://www.dropbox.com/s/7puy5v0v3pk7y6a/nand1-cubietruck-debian-boot.tgz to the root directory. I have tried that, and to my surprise, it worked. I have mentioned before that I am a totally beginner with Linux, and the method was "trail and error". Its maybe just the repeated try to transfer the image which lead to the success, or it was really because of placing the file there.
If one have the same issue, its worth trying it.
Regards
Joe

**Comment by zakora** [comment]
Hi @joetruck, I'm facing the same issue you were having.
I'll try something following your second comment.

Can you clarify a few things?
- When you put the nand-boot.tgz file, did you put it on Cubian or Lubuntu?
- Did you untar/extract this file?
- Where did you put it exactly, i.e. which partition?

Thanks

**Comment by joetruck** [comment]
Hi zakora,
- I placed the file to the /root Folder on my µSD-Card Cubian
- No I have not extracted it
- There are 2 partitions on my 16 GB sd-card, one with 1GB and boot information and one with 7.7  GB. The root folder is in the 7.7 GB partition, and the file is in the root folder

however I have tried to repeat it and it did not work again so I am more and more sure to but the file there does not help. But I managed to get the Cubian nand install done again by flashing lubuntu to the nand an install cubian by repeating this cycle 4 times, so finally Cubian booted from nand now again after the 4. installation. I dont know whats wrong. So if you want ubian on nand take the time and try the lubuntu / cubian cycle. also you should know that at the first boot from nand it takes a few seconds until the first led lights up.
 Good Luck!

**Comment by zakora** [comment]
Thanks for this thorough reply @joetruck.
I finally get it working. I'll put some information here, maybe it will help someone.

The Cubietruck needs a special information at the very beginning of the nand partition in order to boot (something like the MBR I believe).
When we use the nand-install script, this special information is not put into the nand partition, so the Cubietruck cannot boot if it doesn't already have this information.

To put this special information to nand, we must flash the Cubietruck with the lubuntu image using PhoenixSuit/LiveSuit. After that, we can use the standard procedure to install Cubian (well, I installed [CT Debian by Slovenia](http://www.igorpecovnik.com/2013/12/24/cubietruck-debian-wheezy-sd-card-image/) instead, but it should be the same). That is, use `dd` to copy the Cubian image to the SD card, then boot the Cubietruck from the SD card, run the nand-install script, reboot _from the SD card_, run the nand-install again, the reboot _without the SD card_.

PS: I think this issue could be closed now (@cubieplayer @joetruck).

**Comment by joetruck** [comment]
Hi @zakora ,@cubieplayer;

The cubian-nandinstall is a very nice feature, and it would be good if it works properly also on the Cubietruck without the need of a work-around. If you google you can see that there are many arround the globe having the same trouble.
I personally like Cubian because of better compatibility with newer Hardware, (at least in my case e.g it supports out of the box the popular Logitech Wireless Keyboard k400r, Lubuntu doesn't.)
I really hope that development continues and the open issues can be resolved in future upgrades, or new versions.
Thanks for the great work so far!

**Comment by cubieplayer** [comment]
This problem has solved.
Closed duplicated with https://github.com/cubieplayer/Cubian/issues/231
