### ISSUE TITLE
How to check what on what board Cubian is running?

### ISSUE THREAD

**Issue by vsapronov** [cubieplayer/Cubian#308]
I have all 3: cubiboard, cubieboard2 and cubietruck. I'm using Cubian on all of them. How I can figure out on what board my script is executing? I need some shell command which my script can use to see what is the board.

Thanks for any help or advice

**Comment by opless** [comment]
You could try fingerprinting the status "files" in /proc (starting with
cpuinfo) and config.gz

I've only got a couple of cubiboards but if you wanted to check if you were
running on a specific device (rather than family) you could pick out Mac
addresses (ip show link eth0) or the chip id line of /proc/cpuinfo (the
former would work on all Linux distros)

On 17 May 2014, at 05:35, Vladimir Sapronov notifications@github.com
wrote:

I have all 3: cubiboard, cubieboard2 and cubietruck. I'm using Cubian on
all of them. How I can figure out on what board my script is executing? I
need some shell command which my script can use to see what is the board.

Thanks for any help or advice

—
Reply to this email directly or view it on
GitHubhttps://github.com/cubieplayer/Cubian/issues/308
.

**Comment by vsapronov** [comment]
Thanks for advise.

I'm writing a script which need to know on what board it's running. So, it's not like I don't know what is what at my home - I rather trying to get single working script for all cubieboards...

**Comment by vsapronov** [comment]
I end up with this script: https://github.com/syncloud/owncloud-setup/blob/master/cubian-boardname.sh Closing this issue. Thanks!
