### ISSUE TITLE
Fix Ethernet MAC address

### ISSUE THREAD

**Issue by pgauret** [cubieplayer/Cubian#47]
At each reboot the Cubieboard will generate a random MAC address. This is often not desirable. 

I'd suggest that at the first boot, a script captures the randomly generated MAC address and pins it in /etc/network/interfaces using the following syntax.

```
iface eth0 inet dhcp
    hwaddress ether xx:xx:xx:xx:xx:xx
```

As a temporary workaround this could also be added to the documentation.

**Comment by cubieplayer** [comment]
Nice solution

**Comment by phpmysqlfreak** [comment]
Otherwise the mac-address could be set in script.bin - i've done this before testing cubian. but i don't know the used distri anymore :D

**Comment by mathiask88** [comment]
Hi,

i think the MAC address is changed at every boot, because it is generated wit CPU serial and revision. On cubieboard cat /proc/cpuinfo shows only zeros for these values and then the system generates a random address. This is only an idea, because i know this behavior from raspberry pi. The workaround works, but if I unplug and reconnect the ethernet cable I don't get any connection anymore.

Edit: I solved the problem by installing macchanger and creating a skript in /etc/network/if-pre-up.d/ 

<pre>#!/bin/sh
# Set the mac address for eth0
/usr/bin/macchanger --mac xx:xx:xx:xx:xx:xx eth0
</pre>

Now i get a connection even after reconnecting the ethernet cable :)

**Comment by phpmysqlfreak** [comment]
Hello again,

I just found out the way for a fixed mac-address again:

Start the board from an µSD-card, an make sure you are working as root.

mkdir /home/cubie/nandb #create working-directory
mount /dev/nandb /home/cubie/nandb #mount rootfs to working-dir

cp /home/cubie/nandb/boot/script.bin /home/cubie/script.bin.bak #create backup from old binary
bin2fex /home/cubie/nandb/boot/script.bin /home/cubie/script.fex #create fex-file from old config

echo '' >> /home/cubie/script.fex #add an empty line
echo '[dynamic]' >> /home/cubie/script.fex #add [dynamic] section
echo 'MAC = "001122334455"' >> /home/cubie/script.fex #add mac-address definition

fex2bin /home/cubie/script.fex /boot/script.bin #create new binary from fex-config

rsync -avc /boot/script.bin /boot/uEnv.txt /boot/uImage /home/cubie/nandb/boot/

After rebooting from flash the mac-address is fixed. - The extra-entry [dynamic] I found out here:
http://linux-sunxi.org/FirstSteps

**Comment by mathiask88** [comment]
Yes the solution from phpmysqlfreak works great. Maybe you can add some lines to nandinstall skript that generate a script.bin with a random MAC.

**Comment by cubieplayer** [comment]
Needs to fix in next version, ref https://github.com/cubieplayer/Cubian/issues/63

**Comment by deutrino** [comment]
I solved this by just setting it before dhclient asks for an IP from the DHCP server:  make a file in /etc/dhclient/dhclient-enter-hooks.d called e.g. ‘setmac’ and put the following in it, where you PICK the mac address to replace xx in the following:

```
/sbin/ifconfig eth0 hw ether xx:xx:xx:xx:xx:xx
```

Cite: http://blog.gordon.morehouse.me/2013/08/23/my-terrible-no-good-very-bad-non-guide-to-installing-cubian-debian-wheezy-on-the-cubieboard-2/

**Comment by cubieplayer** [comment]
@gordon-morehouse Your solution semms quite succinct, Thanks for sharing.
I combined two solution together. The mac address which is setted in script.bin has the highest priority.
if not set, we will use a temporary static mac address instead. See commit https://github.com/mmplayer/fsupdate/commit/8a6791a0ea683f8d3ce1ee559dcc298899042708

**Comment by deutrino** [comment]
I'm 'marking' the MACs on my cubies by starting them all with 00:B0:91 in the first 3 bytes - this marker belongs to Transmeta Corp, but you could pick any vendor-neutral combo for the first 3 bytes and then set the last 3 bytes as random - that way anybody looking for their Cubie in e.g. static DHCP settings on their router would be able to look for MAC addresses starting with xx:yy:zz if they didn't edit the (semi)-permanent MAC themselves.

**Comment by cubieplayer** [comment]
@gordon-morehouse nice suggestion, I use `c0:b0` as the marker on cubian.

BTW, I found a nice article talking about this issue
http://www.debian-administration.org/article/501/Working_with_MAC_addresses

**Comment by cubieplayer** [comment]
@gordon-morehouse The dhcp-client hook is good, but there is a problem if user configure the interface using static up.
I found a perfect solution to solve all the problems.
If there is a mac address in script.bin, that's good, we do nothing.
If not, then we generate a mac address start with `c0:b0`, save it to a file.At each time system boot up, we will configure the interface using the mac address we saved.

Here is the code
https://github.com/mmplayer/fsupdate/blob/base/common/etc/init.d/cubian-fixrandomemac

**Comment by mholler** [comment]
I tried cubian-fixrandomemac and got it to work from the command line after downing eth0  and then re uping it after  but, it doesn't run when I boot.   I put it in /etc/init.d/ and enabled execution.  I also updated the rc.d files with sudo update-rc.d  cubian-fixrandomemac defaults    Still no luck.  Any help would be appreciated.  There is probably a log file I don't know about with the error message.  Looking...

**Comment by michalliu** [comment]
@mholler have you tried `insserv cubian-fixrandomemac` ?

**Comment by mholler** [comment]
Cubian,
Thanks for the feedback.
No I haven't tried insserv.
It seems like the cubietruck already has created a MAC address and done 
DHCP to get an IP address before  cubian-fixrandomemac runs and since 
eth0 is already up cubian-fixrandomemac is unable to set the MAC address 
and even if it could the cubieTruck would already have an IP address 
which it would need to renew.  By then the damage is done which is that 
my router has added another device entry which I can't delete without 
clearing the whole mac address-IP address table in it.  I'm not sure 
when or how the cubietruck sets its MAC address relative to the rc.d 
start up scripts.

Anyway, thanks again for the tip which I will try.
Mark Holler
Camalie Networks http://camalienetworks.com

P.S.  I like the cubieTruck.   It is a full function Low power Linux 
machine for about $100 where there is a gap in the PC market place.  The 
SATA interface sets it apart from the pcDuino and Raspberry Pi.  I'm 
using it as an XBee Wireless Sensor network gateway and Data Webserver.  
I do wish you would sell a version with Linux installed rather than 
Android.   It took me a day and a half to get Linux running on it.

**Comment by mholler** [comment]
I haven't tried insserv yet but, I did add downing before and  uping after the eth0 MAC address in the cubian-fixrandomemac script which resulted in the cubieTruck ending up with the desired fixed MAC but, apparently a DHCP request using a random MAC address has already taken place by that time and my router won't recognize packets from the cubieTruck with the fixed MAC.   I would think that bringing up eth0 with a new MAC would generate a new DHCP request but, if it does the router isn't making the right connection.  My router is an AT&T Uverse home router which also manages my TV and phone service.  It is very quirky and undocumented to say the least which is most likely where the problem lies.  
http://99.115.132.114/cs3prod.htm
